#!/usr/bin/env python3
"""Draw the PLACEHOLDER art: near-black cards, a purple glow, gold lights.

Palette 5b, as on the site: the page purple (#5a4fc0 to #6a5fd0), cards in
#0d0b1f with a #1c1838 edge lit lavender from above, and gold (#f5c542) for
the small lights. No green or teal anywhere.

These stand in until the AI pictures from tools/art/PROMPTS.md are made.
They are drawn here from shapes, not generated by a model, so they carry no
model licence. Each one is written as a source PNG to the folder given, then
run through build_art.py, which writes the sizes the pages use.

    python3 tools/art/placeholder_art.py /tmp/art-src
"""
import math
import os
import subprocess
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))

PURPLE = (90, 79, 192)        # #5a4fc0, the page colour
PURPLE_2 = (106, 95, 208)     # #6a5fd0
GLOW = (124, 112, 232)        # a lighter purple, for the glow behind things
DEEP = (40, 32, 112)          # a deep purple, for shade
CARD = (13, 11, 31)           # #0d0b1f
CARD_LINE = (28, 24, 56)      # #1c1838
CARD_2 = (23, 20, 47)         # #17142f
QUIET = (46, 40, 86)          # lines on a card
LAVENDER = (185, 179, 230)    # #b9b3e6
GOLD = (245, 197, 66)         # #f5c542
SHADE = (16, 10, 58)


def gradient(w, h, top, bot):
    im = Image.new("RGB", (w, h))
    d = ImageDraw.Draw(im)
    for y in range(h):
        t = y / max(1, h - 1)
        d.line([(0, y), (w, y)], fill=tuple(int(a + (b - a) * t) for a, b in zip(top, bot)))
    return im


def glows(im, spots):
    """Soft light in the background: (cx, cy, r, colour, strength)."""
    w, h = im.size
    for (cx, cy, r, col, a) in spots:
        mask = Image.new("L", (w, h), 0)
        ImageDraw.Draw(mask).ellipse((cx * w - r * w, cy * h - r * w, cx * w + r * w, cy * h + r * w), fill=int(255 * a))
        mask = mask.filter(ImageFilter.GaussianBlur(r * w * 0.6))
        im = Image.composite(Image.new("RGB", (w, h), col), im, mask)
    return im


def grain(im):
    # A little grain so the gradients do not band once compressed.
    # effect_noise is centred on 128, so take 128 back off.
    noise = Image.effect_noise(im.size, 4).convert("RGB")
    return ImageChops.add(im, noise, scale=1.0, offset=-128)


def purple_backdrop(w, h, spots):
    """The page purple, for the hero, which melts into the page."""
    return glows(gradient(w, h, PURPLE, PURPLE_2), spots)


def dark_backdrop(w, h, spots):
    """A near-black card with a purple glow, for pictures that sit on cards."""
    return glows(gradient(w, h, CARD, (18, 15, 42)), spots)


def top_lit(w, h):
    """1.0 at the top edge, fading to nothing at the bottom."""
    return Image.linear_gradient("L").resize((w, h)).point(lambda v: 255 - v)


def drop(mask, dy):
    """Move a mask down by dy without wrapping (ImageChops.offset wraps)."""
    out = Image.new("L", mask.size, 0)
    out.paste(mask, (0, dy))
    return out


def rrect_mask(w, h, box, radius):
    m = Image.new("L", (w * 2, h * 2), 0)
    ImageDraw.Draw(m).rounded_rectangle([v * 2 for v in box], radius=radius * 2, fill=255)
    return m.resize((w, h), Image.LANCZOS)


def poly_mask(w, h, pts):
    m = Image.new("L", (w * 2, h * 2), 0)
    ImageDraw.Draw(m).polygon([(x * 2, y * 2) for x, y in pts], fill=255)
    return m.resize((w, h), Image.LANCZOS)


def ellipse_mask(w, h, box):
    m = Image.new("L", (w * 2, h * 2), 0)
    ImageDraw.Draw(m).ellipse([v * 2 for v in box], fill=255)
    return m.resize((w, h), Image.LANCZOS)


def card(im, mask, fill=CARD, rim=0.55, shadow=0.6):
    """A solid near-black shape with a soft shadow and an edge lit from above."""
    w, h = im.size
    if shadow:
        sh = mask.filter(ImageFilter.GaussianBlur(max(6, min(w, h) * 0.03)))
        sh = drop(sh, int(min(w, h) * 0.03))
        im = Image.composite(Image.new("RGB", (w, h), SHADE), im, sh.point(lambda v: int(v * shadow)))
    im = Image.composite(Image.new("RGB", (w, h), fill), im, mask)
    edge = mask.filter(ImageFilter.FIND_EDGES).filter(ImageFilter.MaxFilter(3))
    im = Image.composite(Image.new("RGB", (w, h), CARD_LINE), im, edge)
    lit = ImageChops.multiply(edge, top_lit(w, h).point(lambda v: int(v * rim)))
    return Image.composite(Image.new("RGB", (w, h), LAVENDER), im, lit)


def light(im, x, y, r, col=GOLD, glow=3.2, strength=0.55):
    """A small lamp: a soft halo and a bright core."""
    w, h = im.size
    m = ellipse_mask(w, h, (x - r * glow, y - r * glow, x + r * glow, y + r * glow)).filter(ImageFilter.GaussianBlur(r * 1.5))
    im = Image.composite(Image.new("RGB", (w, h), col), im, m.point(lambda v: int(v * strength)))
    return Image.composite(Image.new("RGB", (w, h), col), im, ellipse_mask(w, h, (x - r, y - r, x + r, y + r)))


def bar(im, box, col):
    w, h = im.size
    return Image.composite(Image.new("RGB", (w, h), col), im, rrect_mask(w, h, box, (box[3] - box[1]) / 2))


def wallet(cw, ch, lights=1):
    """One card for the hero, drawn flat (place() turns it)."""
    s = 2
    W, H = cw * s, ch * s
    r = int(ch * 0.13 * s)
    shape = Image.new("L", (W, H), 0)
    ImageDraw.Draw(shape).rounded_rectangle((0, 0, W - 1, H - 1), radius=r, fill=255)
    rgb = Image.new("RGB", (W, H), CARD)
    d = ImageDraw.Draw(rgb)
    pad = int(ch * 0.16 * s)
    lh = max(4, int(ch * 0.07 * s))
    # Two quiet lines, like the words on a card.
    d.rounded_rectangle((pad, H - pad - lh * 3.2, pad + W * 0.46, H - pad - lh * 2.2), radius=lh // 2, fill=QUIET)
    d.rounded_rectangle((pad, H - pad - lh, pad + W * 0.28, H - pad), radius=lh // 2, fill=QUIET)
    edge = Image.new("L", (W, H), 0)
    ImageDraw.Draw(edge).rounded_rectangle((0, 0, W - 1, H - 1), radius=r, outline=255, width=2 * s)
    rgb = Image.composite(Image.new("RGB", (W, H), CARD_LINE), rgb, edge)
    lit = ImageChops.multiply(edge, top_lit(W, H).point(lambda v: int(v * 0.55)))
    rgb = Image.composite(Image.new("RGB", (W, H), LAVENDER), rgb, lit)
    rgb = rgb.resize((cw, ch), Image.LANCZOS)
    lr = max(3, int(ch * 0.05))
    for i in range(lights):
        rgb = light(rgb, cw - ch * (0.22 + 0.18 * i), ch * 0.24, lr, GOLD, glow=3.0, strength=0.45)
    out = rgb.convert("RGBA")
    out.putalpha(shape.resize((cw, ch), Image.LANCZOS))
    return out


def place(im, sprite, cx, cy, angle):
    """Drop a sprite centred at (cx, cy), turned by angle, with its shadow."""
    w, h = im.size
    rot = sprite.rotate(angle, resample=Image.BICUBIC, expand=True)
    x, y = int(cx - rot.width / 2), int(cy - rot.height / 2)
    a = Image.new("L", (w, h), 0)
    a.paste(rot.getchannel("A"), (x, y))
    sh = drop(a.filter(ImageFilter.GaussianBlur(min(w, h) * 0.025)), int(min(w, h) * 0.03))
    im = Image.composite(Image.new("RGB", (w, h), SHADE), im, sh.point(lambda v: int(v * 0.55)))
    layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    layer.paste(rot, (x, y), rot)
    return Image.alpha_composite(im.convert("RGBA"), layer).convert("RGB")


def hero(w, h, seed):
    tall = h > w
    im = purple_backdrop(w, h, [
        (0.80, 0.22, 0.42, GLOW, 0.55),
        (0.10, 0.92, 0.45, DEEP, 0.35),
    ])
    s = min(w, h)
    if not tall:
        # Wide screens: the words sit in the middle, the cards at the sides.
        cards = [(0.88, 0.28, 0.24, -12, 2), (0.86, 0.72, 0.20, 7, 1), (0.10, 0.80, 0.18, 10, 1)]
        lamps = [(0.96, 0.90, 0.010), (0.06, 0.22, 0.006), (0.62, 0.94, 0.005)]
    else:
        # Phones: the words fill the middle, so the cards peek in from the edges.
        cards = [(0.98, 0.05, 0.46, -12, 2), (1.02, 0.50, 0.34, 8, 1), (-0.02, 0.92, 0.34, 9, 1)]
        lamps = [(0.08, 0.30, 0.008), (0.93, 0.70, 0.010), (0.55, 0.97, 0.007)]
    for (cx, cy, cwf, ang, n) in cards:
        cw = int(w * cwf)
        im = place(im, wallet(cw, int(cw * 0.62), n), cx * w, cy * h, ang)
    for (lx, ly, lr) in lamps:
        im = light(im, lx * w, ly * h, lr * s * (1.4 if tall else 1.0), GOLD, glow=4.0, strength=0.4)
    return grain(im)


def og_hero(w, h, seed):
    """The home link preview: build_art.py slides the picture right by a
    quarter and writes the words on the left, so the cards sit in the
    middle here and the left quarter stays empty."""
    im = purple_backdrop(w, h, [(0.62, 0.30, 0.42, GLOW, 0.55), (0.10, 0.92, 0.45, DEEP, 0.35)])
    s = min(w, h)
    for (cx, cy, cwf, ang, n) in [(0.56, 0.34, 0.30, -12, 2), (0.64, 0.74, 0.24, 7, 1)]:
        cw = int(w * cwf)
        im = place(im, wallet(cw, int(cw * 0.62), n), cx * w, cy * h, ang)
    for (lx, ly, lr) in [(0.40, 0.14, 0.010), (0.76, 0.92, 0.012)]:
        im = light(im, lx * w, ly * h, lr * s, GOLD, glow=4.0, strength=0.4)
    return grain(im)


def servers(w, h, seed):
    im = dark_backdrop(w, h, [(0.5, 0.45, 0.42, PURPLE, 0.55), (0.85, 0.1, 0.3, GLOW, 0.25)])
    for i in range(3):
        y0 = h * (0.19 + i * 0.22)
        im = card(im, rrect_mask(w, h, (w * 0.24, y0, w * 0.76, y0 + h * 0.17), h * 0.035))
        for j in range(3):
            gold = j < 2
            im = light(im, w * (0.30 + j * 0.035), y0 + h * 0.085, h * 0.011, GOLD if gold else LAVENDER,
                       glow=3.0, strength=0.45 if gold else 0.25)
        for k in range(4):
            x = w * (0.48 + k * 0.06)
            im = bar(im, (x, y0 + h * 0.072, x + w * 0.04, y0 + h * 0.098), QUIET)
    return grain(im)


def bots(w, h, seed):
    im = dark_backdrop(w, h, [(0.5, 0.45, 0.42, PURPLE, 0.55), (0.15, 0.15, 0.28, GLOW, 0.2)])
    m = rrect_mask(w, h, (w * 0.26, h * 0.18, w * 0.74, h * 0.70), h * 0.09)
    tail = poly_mask(w, h, [(w * 0.34, h * 0.66), (w * 0.30, h * 0.84), (w * 0.44, h * 0.68)])
    im = card(im, ImageChops.lighter(m, tail))
    plane = poly_mask(w, h, [(w * 0.40, h * 0.46), (w * 0.62, h * 0.32), (w * 0.55, h * 0.58), (w * 0.50, h * 0.50)])
    halo = plane.filter(ImageFilter.GaussianBlur(h * 0.03))
    im = Image.composite(Image.new("RGB", (w, h), GOLD), im, halo.point(lambda v: int(v * 0.35)))
    im = Image.composite(Image.new("RGB", (w, h), GOLD), im, plane)
    im = light(im, w * 0.82, h * 0.26, h * 0.016, GOLD, glow=4.0, strength=0.4)
    return grain(im)


def tools(w, h, seed):
    im = dark_backdrop(w, h, [(0.5, 0.45, 0.42, PURPLE, 0.55), (0.85, 0.85, 0.28, GLOW, 0.22)])
    cx, cy, r = w * 0.5, h * 0.48, h * 0.30
    hexa = [(cx + r * math.cos(math.radians(a)), cy + r * math.sin(math.radians(a))) for a in range(30, 390, 60)]
    im = card(im, poly_mask(w, h, hexa))
    outer = ellipse_mask(w, h, (cx - r * 0.45, cy - r * 0.45, cx + r * 0.45, cy + r * 0.45))
    inner = ellipse_mask(w, h, (cx - r * 0.40, cy - r * 0.40, cx + r * 0.40, cy + r * 0.40))
    im = Image.composite(Image.new("RGB", (w, h), LAVENDER), im, ImageChops.subtract(outer, inner))
    im = Image.composite(Image.new("RGB", (w, h), CARD_2), im, inner)
    beam = poly_mask(w, h, [(cx + r * 0.3, cy + r * 0.3), (w * 0.95, h * 0.95), (w * 0.82, h * 1.0)]).filter(ImageFilter.GaussianBlur(6))
    im = Image.composite(Image.new("RGB", (w, h), GOLD), im, beam.point(lambda v: int(v * 0.32)))
    im = light(im, cx, cy, h * 0.03, GOLD, glow=3.5, strength=0.45)
    return grain(im)


def plumb(w, h, seed):
    im = dark_backdrop(w, h, [(0.5, 0.5, 0.42, PURPLE, 0.55), (0.5, 0.0, 0.3, GLOW, 0.25)])
    ImageDraw.Draw(im).line([(w * 0.5, 0), (w * 0.5, h * 0.36)], fill=LAVENDER, width=max(2, w // 400))
    bob = [(w * 0.5, h * 0.36), (w * 0.60, h * 0.52), (w * 0.5, h * 0.86), (w * 0.40, h * 0.52)]
    im = card(im, poly_mask(w, h, bob), rim=0.7)
    cm = poly_mask(w, h, [(w * 0.5, h * 0.47), (w * 0.535, h * 0.56), (w * 0.5, h * 0.70), (w * 0.465, h * 0.56)])
    im = Image.composite(Image.new("RGB", (w, h), GOLD), im, cm.filter(ImageFilter.GaussianBlur(h * 0.03)).point(lambda v: int(v * 0.45)))
    im = Image.composite(Image.new("RGB", (w, h), GOLD), im, cm.filter(ImageFilter.GaussianBlur(2)))
    im = card(im, rrect_mask(w, h, (w * 0.08, h * 0.88, w * 0.92, h * 0.94), h * 0.03), shadow=0.4)
    return grain(im)


def quay(w, h, seed):
    im = dark_backdrop(w, h, [(0.5, 0.40, 0.40, PURPLE, 0.55), (0.1, 0.1, 0.3, DEEP, 0.3)])
    hz = h * 0.42
    d = ImageDraw.Draw(im)
    for i in range(14):
        y = hz + (h - hz) * (i / 14) ** 1.6 + 4
        f = 0.35 + 0.4 * i / 14
        d.line([(w * 0.04, y), (w * 0.96, y)], fill=tuple(int(c * f) for c in PURPLE_2), width=1)
    pier = [(w * 0.47, hz), (w * 0.53, hz), (w * 0.80, h), (w * 0.20, h)]
    im = card(im, poly_mask(w, h, pier), rim=0.6)
    refl = poly_mask(w, h, [(w * 0.495, hz + 6), (w * 0.505, hz + 6), (w * 0.52, h * 0.7), (w * 0.48, h * 0.7)]).filter(ImageFilter.GaussianBlur(4))
    im = Image.composite(Image.new("RGB", (w, h), GOLD), im, refl.point(lambda v: int(v * 0.35)))
    im = light(im, w * 0.5, hz - h * 0.03, h * 0.02, GOLD, glow=4.0, strength=0.5)
    return grain(im)


JOBS = [
    ("hero-wide", hero, (1920, 1080)),
    ("hero-tall", hero, (900, 1200)),
    ("svc-servers", servers, (1200, 750)),
    ("svc-bots", bots, (1200, 750)),
    ("svc-tools", tools, (1200, 750)),
    ("plumb", plumb, (1200, 750)),
    ("quay", quay, (1200, 750)),
    ("og-home", og_hero, (1200, 630)),
    ("og-plumb", plumb, (1200, 630)),
    ("og-quay", quay, (1200, 630)),
]


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    out = argv[1]
    os.makedirs(out, exist_ok=True)
    for i, (name, fn, (w, h)) in enumerate(JOBS):
        src = os.path.join(out, name + ".png")
        fn(w, h, 35 + i).save(src)
        subprocess.check_call([sys.executable, os.path.join(HERE, "build_art.py"), name, src])
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
